spring:
  application:
    name: MicroMarket

  datasource:
    url: jdbc:mysql://localhost:3306/MicroMarket
    username: root
    password: Jesus4488
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    propoties:
      hibernate:
        format-sql: true


server:
  port: 9090
  servlet:
    context-path: /api/1v/MicroMarket

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE